project/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='home'),
]

project/project/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import include
from django.contrib.auth import views as auth_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls'), name='home'),
]

project/course/models.py
from django.db import models

# Create your models here.
class course(models.Model):
    time = models.IntegerField('회차', primary_key=True)
    course_start_date = models.DateField('시작일')
    course_end_date = models.DateField('종료일')
    course_place = models.CharField('장소', max_length=100)

    def __str__(self):
        return "{}회차 ({} ~ {})".format(self.time, self.course_start_date, self.course_end_date)

project/exchange/models.py
from django.db import models
from django.contrib.auth.models import User
from course.models import course

# Create your models here.
class exchange(models.Model):
    user = models.ForeignKey(User)
    haveTime = models.ForeignKey(course, related_name='haveTime')
    wishTimeCheck = models.BooleanField("원하는 시간이 있습니까?", default=True)
    wishTime1 = models.ForeignKey(course, related_name='wishTime1', blank=True, null=True, default=None)
    wishTime2 = models.ForeignKey(course, related_name='wishTime2', blank=True, null=True, default=None)

    def __str__(self):
        return "{} from {}".format(self.id, self.user)

project/home/models.py
from django.db import models

# Create your models here.

project/home/forms.py
from django import forms

class RegistrationForm(forms.Form):
    username = forms.CharField(label='name', max_length=30)
    email = forms.EmailField(label='email')
    password = forms.CharField(label='password', widget=forms.PasswordInput())
    password_check = forms.CharField(label='password_check', widget=forms.PasswordInput())

project/course/views.py
from django.shortcuts import render

# Create your views here.

project/exchange/views.py
from django.shortcuts import render

# Create your views here.

project/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
    }
    return render(request, 'home/index.html', context)

project/templates/home/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>SSE - {% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<style>
    .navbar {
        padding-top: 5px !important;
        padding-bottom: 0 !important;
        height: 50px;
    }
</style>

<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand">
            <a href=" {% url 'home:home' %} ">
                COR1007-Exchange
            </a>
        </a>
    </div>
    <div class="collapse    navbar-collapse navbar-es1-collapse">
        <ul class="nav navbar-nav navbar-right">
            <!--
                <li> <a data-toggle="modal" href="#login">로그인</a> </li>
                <li> <a data-toggle="modal" href="#signin">회원가입</a> </li>
            -->
            {% if user.is_active %}
                <a href="{'''% url 'logout' %'''}">
                    {% firstof user.username %}님 안녕하세요.
                </a>
                <a href="{% url 'logout' %}">
                    <button type="button" class="btn btn-link btn-lg">로그아웃</button>
                </a>

            {% else %}
                <a href="{'''% url 'users:logout' %'''}">
                    <button type="button" class="btn btn-link btn-lg">회원가입</button>
                </a>
                <a href="{% url 'login' %}">
                    <button type="button" class="btn btn-link btn-lg">로그인</button>
                </a>
            {% endif %}
        </ul>

    </div>
</nav>

{% block content %} {% endblock %}
{% block footer %} {% endblock %}

</body>
</html>

project/templates/home/index.html
{% extends "home/base.html" %}

{% block title %}서강대학교 성찰과 성장 교환소{% endblock %}

<style>
    .margin-top-10 {
        margin-top: 10px;
    }

    .margin-top-0 {
        margin-top: 0;
    }

    footer {
        margin-top: 10px;
        padding: 20px;
        border-top: 1px solid #ccc;
    }
</style>

{% block content %}
    <div class="container">

        <footer class="text-center">
            copyright&copy 2017 kepler. All rights are reserved.
        </footer>
    </div>
{% endblock %}